include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Code Style
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # Best Practices
    always_declare_return_types: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_relative_imports: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true

    # Documentation
    public_member_api_docs: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: error
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
    throw_of_invalid_type: error
